### ISSUE TITLE
Setup habitat bldr with operator in k8s

### ISSUE THREAD

**Issue by indradhanush** [kinvolk/habitat-builder-to-kubernetes#3]
**Goals:**

-  [x] Setup k8s cluster on GCE
-  [x] Setup habitat-operator
-  [ ] Setup habitat bldr
-  [ ] Play around with nginx package for habitat
-  [ ] Document the steps
-  [ ] Automate this eventually

**Comment by schu** [comment]
Not being worked on atm, closing. Can be re-opened later if necessary.
