### ISSUE TITLE
Planning for Habitat Builder Demo

### ISSUE THREAD

**Issue by robertgzr** [kinvolk/habitat-builder-to-kubernetes#5]
- [ ] verify habitat [vagrantfile](https://github.com/kinvolk/habitat/blob/master/Vagrantfile) [ @indradhanush ]
https://github.com/kinvolk/habitat/blob/755aeff62e170544cf967eb4155a60de20cfe434/scripts/vagrant/README.md
  - [ ] env setup works
  - [ ] build works `make build-bin build-srv`
  - [ ] can run bldr `make bldr-run-no-build`
https://github.com/kinvolk/habitat/blob/dongsu/docs-setup-builder/scripts/bldr/SETUP_BLDR.md

- [ ] integrate kubernetes exporter [ @robertgzr @dongsupark ]
https://github.com/kinvolk/habitat/tree/robertgzr/kubernetes-runner
  - [ ] can create k8s manifest
  - [ ] can apply manifest to cluster

- [ ] setup kube-spawn cluster \w habitat-operator [ @nhlfr ] https://github.com/kinvolk/habitat-builder-to-kubernetes/issues/6
- [ ] update habitat deployments using new promote crd [ @nhlfr ] 
https://github.com/kinvolk/habitat-operator/pull/128

- [ ] prepare demo script: autom. deploy from bldr to cluster
  - [ ] also include promotion across channels

- [ ] add an additional target bldr-kill for better usability ( @dongsupark ) https://github.com/habitat-sh/habitat/pull/4115

---
General design and research: https://docs.google.com/document/d/14BdVNctDoR96Z8l_NrUhS9EMNA8mWk21Khe5ogY61lk/edit
Task status: https://docs.google.com/document/d/1FUjyFZw4N8NdNMKTtHEUoX1oDm6kTxu3o8fv3qiub1Q/edit

**Comment by schu** [comment]
Issue not actually used for planning, closing.
