### ISSUE TITLE
Update Vagrantfile to automate habitat builder setup

### ISSUE THREAD

**Issue by dongsupark** [kinvolk/habitat-builder-to-kubernetes#6]
We need to update Vagrantfile in the habitat repo, to be able to automate the highly complicated habitat builder setup.

For now @indradhanush @nhlfr @dongsupark is working on it.
What needs to be done:

* [ ] Fix bugs w.r.t. port forwarding in Vagrantfile https://github.com/habitat-sh/habitat/issues/4107 https://github.com/habitat-sh/habitat/pull/4098 (@dongsupark)
* [x] Make it work with the current master branch of Habitat, 0.40. (@dongsupark)
* [ ] Fixes for running kube-spawn inside the VM, e.g. upgrading Ubuntu to 17.10, disabling systemd-resolved (@nhlfr)
* [ ] Update setup documents https://github.com/kinvolk/habitat/blob/dongsu/docs-setup-builder/scripts/bldr/SETUP_BLDR.md#kill-all-the-builder-daemons (@dongsupark @indradhanush )

**Comment by schu** [comment]
We have a woring pull request upstream: https://github.com/habitat-sh/habitat/pull/4161 Closing.
